config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'gantt_charts#index'
  get 'new', to: 'gantt_charts#new', as: 'new_gantt_chart'
  get ':uid', to: 'gantt_charts#show', as: 'show_gantt_chart'
  get ':uid/edit', to: 'gantt_charts#edit', as: 'edit_gantt_chart'
  get ':uid/new', to: 'tasks#new', as: 'new_task'
  put ':uid', to: 'gantt_charts#save_tasks'
  post ':uid/new', to: 'tasks#create', as: 'create_task'

  resources :gantt_charts, only: [:create, :edit, :update]
  # resources :tasks, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gantt_chart.rb
class GanttChart < ApplicationRecord
  has_many :tasks

  validates :name, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates_with EndNotBeforeStart
  validate :at_least_one_day
  validate :not_longer_than_one_week

  before_create :add_uid

  def self.gen_uid
    Digest::SHA1.hexdigest("#{self.name}-#{Time.current.usec}")[0..5]
  end

  def self.uid_exists?(uid)
    !self.find_by_uid(uid).blank?
  end

  private
  def add_uid
    if self.uid.blank? 
      self.uid = GanttChart.gen_uid
      while GanttChart.uid_exists?(self.uid)
        self.uid = GanttChart.gen_uid
      end
    end
  end

  def at_least_one_day
    if self.start && self.end && (self.end - self.start < 1)
      errors.add(:end, "project length can't be less than a day")
    end
  end

  def not_longer_than_one_week
    if self.start && self.end && (self.end - self.start > 7)
      errors.add(:end, "project length can't be longer than a week")
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :gantt_chart

  validates :name, presence: true
  validates :start, presence: true
  validates :end, presence: true

  validates_with NotBeforeProjectStart
  validates_with NotAfterProjectEnd
  validates_with EndNotBeforeStart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gantt_charts_controller.rb
class GanttChartsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
  end

  def edit
    @gantt_chart = GanttChart.find_by_uid(params[:uid])
  end

  def new
    @gantt_chart = GanttChart.new
  end

  def update
    @gantt_chart = GanttChart.find(params[:id])
    gantt_params = params[:gantt_chart].permit('name', 'start', 'end')

    begin
      @gantt_chart.update!(gantt_params) 
    rescue ActiveRecord::RecordInvalid => e
      flash.alert = e.message
      return redirect_to edit_gantt_chart_path
    end

    redirect_to show_gantt_chart_path(@gantt_chart.uid)
  end

  def create
    gantt_params = params[:gantt_chart].permit('name', 'start', 'end')

    begin
      @gantt_chart = GanttChart.create!(gantt_params)
    rescue ActiveRecord::RecordInvalid => e
      flash.alert = e.message
      return redirect_to new_gantt_chart_path
    end

    redirect_to show_gantt_chart_path(@gantt_chart.uid)
  end

  def save_tasks
    @gantt_chart = GanttChart.find_by_uid(params[:uid])

    puts 'save_tasks'

    tasks = params[:tasks].map do |task|
      {
        name: task[:name],
        start: task[:start],
        end:  task[:end] 
      } 
    end

    puts 'tasks'
    puts tasks

    unless tasks
      return render json: { success: false }
    end

    @gantt_chart.tasks.destroy_all
    puts tasks
    @gantt_chart.tasks.create!(tasks)

    render json: { success: true }
  end

  def show
    @gantt_chart = GanttChart.find_by_uid(params[:uid])

    @gantt_chart_props = {
      tasks: @gantt_chart.tasks.to_a,
      start: @gantt_chart.start,
      end: @gantt_chart.end
    }
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @gantt_chart = GanttChart.find_by_uid(params[:uid])
    @task = Task.new
    @task.gantt_chart_id = @gantt_chart.id
  end

  def create
    task_params = params[:task].permit('name', 'start', 'end', 'gantt_chart_id')
    @gantt_chart = GanttChart.find_by_uid(params[:uid])

    begin
      @task = Task.create!(task_params)
    rescue ActiveRecord::RecordInvalid => e
      flash.alert = e.message
      return redirect_to new_task_path(@gantt_chart.uid)
    end

    redirect_to show_gantt_chart_path(@gantt_chart.uid)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gantt_charts/_form.html.erb
<%= form_for(@gantt_chart) do |f| %>
  <%= f.label 'Project Name' %>
  <div class='input-group input-group-lg'>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
  </div>

  <%= f.label 'Project Start' %>
  <%= f.date_field :start, class: 'form-control', placeholder: 'Name' %>

  <%= f.label 'Project End' %>
  <%= f.date_field :end, class: 'form-control', placeholder: 'Name' %>

  <div class='row' style='margin-top:25px;'>
    <div class='col text-right'>
      <button class='btn btn-lg btn-primary' type='submit'>Submit</button>
    </div>
  </div>
<% end %>

app/views/gantt_charts/edit.html.erb
<div class='container'>
  <div class='row' style='margin-top:25px'>
    <div class='col'></div>
    <div class='col'>
      <h3>Edit Gantt Chart: <%= @gantt_chart.name %></h3>
      <%= render 'form' %>
    </div>
    <div class='col'></div>
  </div>
</div>

app/views/gantt_charts/index.html.erb
<div class='container'>

  <div class='row' style='margin-top:25px'>
    <div class='col'>
      <h3>Welcome to Gantty</h3>
      <p>Make awesome gantt charts for free.</p>
    </div>
  </div>

  <div class='row'>
    <div class='col'>
      <h3>How To:</h3>
      <ol>
        <li>Click "New Chart" in the top right</li>
        <li>Enter a project name, and a start / end date</li>
      </ol>
    </div>
  </div>
  
  <div class='row'>
    <div class='col'>
      <h5>Current Limitiations</h5>
      <ul>
        <li>Projects can be no longer than 7 days</li>
        <li>Projects must be at least 1 day</li>
        <li>Tasks must be at least one hour long</li>
        <li>Tasks can only be in multiples of 1 hour increments</li>
      </ul>
    </div>
  </div>
</div>

app/views/gantt_charts/new.html.erb
<div class='container'>
  <div class='row' style='margin-top:25px'>
    <div class='col'></div>
    <div class='col-6'>
      <h3>New Gantt Chart</h3>
    </div>
    <div class='col'></div>
  </div>
  <div class='row'>
    <div class='col'></div>
    <div class='col-6'>
      <%= render 'form' %>
    </div>
    <div class='col'></div>
  </div>
</div>

app/views/gantt_charts/show.html.erb
<div class='text-center'>
  <h3>Showing: <%= @gantt_chart.name %></h3>

  <%= link_to new_task_path(@gantt_chart.uid) do %>
    <button class='btn btn-primary'>Add Task</button>
  <% end %>

  <%= link_to edit_gantt_chart_path(@gantt_chart.uid) do %>
    <button class='btn btn-primary'>Edit Chart</button>
  <% end %>
</div>
<%= react_component("GanttChart", props: @gantt_chart_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GanttApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/alert' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_alert.html.erb
<% if flash.alert %>
  <div class="alert alert-danger text-center">
    <strong>Oh snap! </strong><%= flash.alert %>
  </div>
</div>
<% elsif flash.notice %>
  <div class="alert alert-info text-center">
    <strong>Notice: </strong><%= flash.notice %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class='navbar navbar-toggleable-md navbar-light bg-faded'>
  <div class='container'>
    <%= link_to root_path, class: 'navbar-brand' do %>
      Gantty
    <% end %>
    <ul class='navbar-nav mr-auto'>
    </ul>
    <form class='form-inline'>
      <%= link_to new_gantt_chart_path do %>
        <button class='btn btn-outline-primary'>New Chart</button>
      <% end %>
    </form>
  </div>
</nav>

app/views/tasks/new.html.erb
<div class='container'>
  <div class='row' style='margin-top:25px'>
    <div class='col'></div>
    <div class='col'>
      <%= form_for(@task, url: { to: create_task_path}) do |f| %>
        <h3>New Task</h3>
        <%= f.label 'Name' %>
        <div class='input-group input-group-lg'>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
        </div>

        <%= f.label 'Start' %>
        <%= f.datetime_field :start, class: 'form-control', placeholder: 'Name' %>

        <%= f.label 'End' %>
        <%= f.datetime_field :end, class: 'form-control', placeholder: 'Name' %>

        <%= f.hidden_field :gantt_chart_id %>

        <div class='row' style='margin-top:25px;'>
          <div class='col text-right'>
            <button class='btn btn-lg btn-primary' type='submit'>Submit</button>
          </div>
        </div>
      <% end %>
    </div>
    <div class='col'></div>
  </div>
</div>